/* ===== ROUTINE DATA ===== */
const ROUTINE = {
  1:{
    name:'Torso Fuerza',
    emoji:'💪',
    sub:'Pecho · Espalda · Hombros · Core',
    exercises:[
      {id:'e1_1',name:'Press banca',sets:5,reps:'5',rest:180,hint:'RIR 1-2'},
      {id:'e1_2',name:'Dominada con lastre o bodyweight',sets:4,reps:'5-6',rest:180,hint:'añadir +5kg cuando hagas 4×6 limpio'},
      {id:'e1_2b',name:'Remo Pendlay / Remo barra',sets:4,reps:'6-8',rest:180},
      {id:'e1_3',name:'Press militar mancuernas',sets:3,reps:'6-8',rest:150},
      {id:'e1_5',name:'Elevación lateral cable',sets:3,reps:'12-15',rest:75},
      {id:'e1_6',name:'Face pulls',sets:3,reps:'15',rest:75},
      {id:'e1_dead',name:'Dead hang',sets:3,reps:'max seg',rest:60,type:'time',hint:'escápulas activas, agarre prono'},
      {id:'e1_7',name:'Cable crunch (polea)',sets:3,reps:'10-12',rest:60},
      {id:'e1_8',name:'Pallof press (polea)',sets:3,reps:'10/lado',rest:60},
      {id:'e1_9',name:'Leg raise colgado',sets:3,reps:'8-12',rest:60},
    ]
  },
  2:{
    name:'Pierna Fuerza + Hipertrofia',
    emoji:'🦵',
    sub:'Cuádriceps · Glúteos · Isquios · Bíceps · Gemelos',
    exercises:[
      {id:'e2_pull',name:'Dominada bodyweight',sets:3,reps:'5',rest:120,hint:'grease the groove, submáximo'},
      {id:'e2_7',name:'Extensión cuádriceps unilateral',sets:2,reps:'15',rest:60,hint:'parcial estirada, pre-activación antes de sentadilla'},
      {id:'e2_1',name:'Sentadilla barra',sets:4,reps:'5-6',rest:210,hint:'RIR 1-2'},
      {id:'e2_2',name:'Hip thrust barra',sets:4,reps:'6-10',rest:180},
      {id:'e2_3',name:'Peso muerto rumano (RDL)',sets:3,reps:'6-8',rest:180},
      {id:'e2_4',name:'Prensa pies bajos',sets:3,reps:'8-10',rest:150},
      {id:'e2_5',name:'Curl femoral sentado',sets:3,reps:'10-12',rest:90},
      {id:'e5_2',name:'Búlgara mancuernas',sets:3,reps:'8-10/pierna',rest:120,hint:'controla la rodilla delantera'},
      {id:'e5_6',name:'Abducción máquina',sets:3,reps:'15-20',rest:60},
      {id:'e2_6',name:'Gemelo de pie',sets:4,reps:'12-15',rest:60,hint:'pausa 2s abajo'},
      {id:'e5_7',name:'Gemelo sentado',sets:3,reps:'15-20',rest:60},
      {id:'e5_curl',name:'Curl en polea baja',sets:3,reps:'12',rest:75,hint:'bíceps en posición estirada, frecuencia 2x'},
    ]
  },
  3:{name:'Descanso',emoji:'😴',sub:'Día off · recuperación activa opcional',rest:true},
  4:{
    name:'Torso Hipertrofia',
    emoji:'🔥',
    sub:'Pecho · Espalda · Hombros · Brazos · Core',
    exercises:[
      {id:'e4_1',name:'Press inclinado mancuernas',sets:4,reps:'8-10',rest:150},
      {id:'e4_cross',name:'Aperturas cable bajo→alto',sets:3,reps:'12-15',rest:90,hint:'pecho estirado, codos ligeramente flexionados'},
      {id:'e4_2',name:'Remo polea al pecho',sets:4,reps:'10-12',rest:120},
      {id:'e4_neutral',name:'Jalón agarre neutro',sets:3,reps:'10-12',rest:120,hint:'complementa dominada del D1'},
      {id:'e4_4',name:'Elevación lateral inclinada cable',sets:3,reps:'12-15',rest:75},
      {id:'e4_5',name:'Face pulls',sets:3,reps:'15',rest:75},
      {id:'e4_6',name:'Curl inclinado mancuernas',sets:3,reps:'8-10',rest:90,hint:'rango estirado, clave para bíceps'},
      {id:'e4_hammer',name:'Curl martillo con cuerda',sets:3,reps:'10-12',rest:75,hint:'alterna con Curl EZ cada semana'},
      {id:'e4_7',name:'Curl EZ barra',sets:2,reps:'10-12',rest:75},
      {id:'e4_8',name:'Extensión overhead cable',sets:3,reps:'10-12',rest:90},
      {id:'e4_9',name:'Pressdown cuerda',sets:2,reps:'12-15',rest:60,hint:'dropset última serie opcional'},
      {id:'e4_neg',name:'Negativas de dominada',sets:3,reps:'3-5',rest:90,hint:'5 segundos bajando controlado'},
      {id:'e4_10',name:'Rueda abdominal',sets:3,reps:'8-12',rest:60},
      {id:'e4_11',name:'Copenhagen plank',sets:2,reps:'20s/lado',rest:45,type:'time'},
      {id:'e4_12',name:'Woodchopper polea',sets:3,reps:'10/lado',rest:60},
    ]
  },
  5:{name:'Descanso',emoji:'😴',sub:'Día off — o sesión opcional de hombro/brazo si querés',rest:true},
  6:{
    name:'Hombro/Brazo/Core + LISS',
    emoji:'⚡',
    sub:'OPCIONAL · 45-60 min',
    exercises:[
      {id:'e6_1',name:'Elevación lateral cable unilateral',sets:4,reps:'12-15',rest:75,hint:'dropset última'},
      {id:'e6_2',name:'Press Arnold',sets:3,reps:'8-10',rest:90},
      {id:'e6_3',name:'Curl martillo con cuerda',sets:3,reps:'10-12',rest:75},
      {id:'e6_4',name:'Extensión overhead cable',sets:3,reps:'10-12',rest:75},
      {id:'e6_5',name:'Cable crunch',sets:3,reps:'10-12',rest:60},
      {id:'e6_6',name:'Pallof press',sets:3,reps:'10/lado',rest:60},
      {id:'e6_7',name:'LISS bici/elíptica',sets:1,reps:'30-40min',rest:0,type:'time',hint:'65-75% FCmax'},
    ]
  },
  7:{name:'Descanso',emoji:'😴',sub:'Día off',rest:true}
};

const TECH_OPTIONS = [
  {id:'fallo',label:'Al fallo'},
  {id:'dropset',label:'Drop set'},
  {id:'restpause',label:'Rest-pause'},
  {id:'myoreps',label:'Myo-reps'},
  {id:'cluster',label:'Cluster'},
  {id:'partials',label:'Parciales estirados'},
  {id:'tempo',label:'Tempo lento'},
  {id:'prefatiga',label:'Pre-fatiga'},
  {id:'postfatiga',label:'Post-fatiga'},
];

const ALTERNATIVES = {
  'e1_1':['Press mancuernas plano','Press en máquina'],
  'e1_2':['Dominada con banda de asistencia','Jalón pronado'],
  'e1_3':['Press Arnold sentado','Press máquina hombro'],
  'e1_5':['Elevación lateral mancuerna','Elevación lateral cable cruzado','Elevación lateral máquina'],
  'e2_1':['Hack squat','Prensa pies bajos'],
  'e2_2':['Hip thrust unilateral','B-stance hip thrust'],
  'e2_3':['Stiff-leg deadlift','Buenos días con barra'],
  'e2_4':['Extensión cuádriceps','Sentadilla búlgara'],
  'e2_5':['Curl femoral tumbado','Hiperextensiones 45°'],
  'e2_6':['Gemelo en prensa','Donkey calf raise'],
  'e5_2':['Step-up controlado','Zancadas (si rodillas OK)'],
  'e5_curl':['Curl concentrado','Curl predicador'],
  'e4_1':['Press inclinado en máquina','Press inclinado barra'],
  'e4_cross':['Aperturas mancuernas inclinado','Pec-deck máquina'],
  'e4_2':['Remo unilateral mancuerna','Remo T-bar pecho apoyado'],
  'e4_neutral':['Jalón pronado','Remo agarre supino'],
  'e4_4':['Elevación lateral mancuerna','Elevación lateral máquina'],
  'e4_5':['Pájaros mancuernas','Reverse pec-deck'],
  'e4_6':['Curl en polea baja','Curl predicador'],
  'e4_hammer':['Curl martillo mancuernas','Curl predicador'],
  'e4_7':['Curl martillo','Curl en polea'],
  'e4_8':['Extensión tríceps mancuerna overhead','Press cerrado barra'],
  'e4_9':['Fondos en paralelas (torso recto)','Extensión tríceps en máquina'],
  'e6_1':['Elevación lateral mancuerna','Elevación lateral máquina'],
  'e6_2':['Press militar mancuernas','Press máquina hombro'],
  'e6_3':['Curl mancuernas alterno','Curl barra EZ'],
  'e6_4':['Extensión tríceps mancuerna','Press cerrado Smith'],
};

const CYCLES = {
  pierna:      {label:'Laboral + Pierna',   kcal:2550, p:190, c:290, f:65},
  torso:       {label:'Laboral + Torso',    kcal:2350, p:190, c:250, f:60},
  laboral:     {label:'Laboral sin entreno',kcal:2100, p:190, c:205, f:55},
  off_pierna:  {label:'Off + Pierna',       kcal:2400, p:190, c:265, f:60},
  off_torso:   {label:'Off + Torso',        kcal:2200, p:190, c:225, f:57},
  off:         {label:'Off sin entreno',    kcal:1950, p:190, c:175, f:52},
};

const SUPPS = [
  {id:'creatina',name:'Creatina',dose:'5 g'},
  {id:'omega3',name:'Omega-3 (EPA+DHA)',dose:'2-3 g'},
  {id:'vitd',name:'Vitamina D3',dose:'2000-4000 UI'},
  {id:'colageno',name:'Colágeno + Vit C',dose:'10 g + 50 mg · pre-entreno'},
  {id:'cafeina',name:'Cafeína',dose:'270-540 mg · pre-entreno'},
  {id:'whey',name:'Whey protein',dose:'si falta proteína'},
  {id:'magnesio',name:'Magnesio glicinato',dose:'200 mg · noche'},
  {id:'curcumina',name:'Curcumina (opcional)',dose:'500-1000 mg'},
];

const EXERCISE_LIBRARY = {
  'Pecho':[
    {name:'Press banca barra',sets:4,reps:'5-6',rest:180},
    {name:'Press banca mancuernas',sets:4,reps:'8-10',rest:150},
    {name:'Press inclinado mancuernas',sets:4,reps:'8-10',rest:150},
    {name:'Press inclinado barra',sets:4,reps:'6-8',rest:180},
    {name:'Press inclinado máquina',sets:3,reps:'10-12',rest:120},
    {name:'Aperturas cable bajo→alto',sets:3,reps:'12-15',rest:75},
    {name:'Aperturas mancuernas inclinado',sets:3,reps:'12-15',rest:75},
    {name:'Fondos en paralelas',sets:3,reps:'8-12',rest:120},
    {name:'Press en máquina pecho',sets:3,reps:'10-12',rest:120},
    {name:'Pullover mancuerna',sets:3,reps:'12',rest:90},
  ],
  'Espalda':[
    {name:'Dominada pronada lastrada',sets:4,reps:'6-8',rest:180},
    {name:'Jalón pronado',sets:4,reps:'8-10',rest:150},
    {name:'Jalón supino',sets:3,reps:'8-10',rest:120},
    {name:'Jalón neutro',sets:3,reps:'10-12',rest:120},
    {name:'Remo con barra Pendlay',sets:4,reps:'6-8',rest:180},
    {name:'Remo T-bar',sets:4,reps:'8-10',rest:150},
    {name:'Remo unilateral mancuerna',sets:3,reps:'10-12',rest:90},
    {name:'Remo polea al pecho',sets:4,reps:'10-12',rest:120},
    {name:'Pullover polea alta',sets:3,reps:'12',rest:90,hint:'lengthened'},
    {name:'Face pulls',sets:3,reps:'15',rest:75},
    {name:'Remo pecho apoyado',sets:3,reps:'10-12',rest:120},
  ],
  'Hombros':[
    {name:'Press militar mancuernas sentado',sets:3,reps:'6-8',rest:150},
    {name:'Press Arnold',sets:3,reps:'8-10',rest:120},
    {name:'Press militar barra',sets:4,reps:'5-6',rest:180},
    {name:'Press máquina hombro',sets:3,reps:'10-12',rest:120},
    {name:'Elevación lateral mancuerna',sets:3,reps:'12-15',rest:75},
    {name:'Elevación lateral cable',sets:3,reps:'12-15',rest:75},
    {name:'Elevación lateral inclinada cable',sets:3,reps:'12-15',rest:75,hint:'delt medial estirado'},
    {name:'Elevación lateral máquina',sets:3,reps:'12-15',rest:75},
    {name:'Pájaros mancuernas',sets:3,reps:'12-15',rest:75},
    {name:'Reverse pec-deck',sets:3,reps:'15',rest:60},
  ],
  'Bíceps':[
    {name:'Curl inclinado mancuernas',sets:3,reps:'8-10',rest:90,hint:'lengthened'},
    {name:'Curl barra EZ',sets:3,reps:'10-12',rest:90},
    {name:'Curl martillo mancuernas',sets:3,reps:'10-12',rest:75},
    {name:'Curl martillo con cuerda',sets:3,reps:'10-12',rest:75},
    {name:'Curl en polea baja',sets:3,reps:'12',rest:75},
    {name:'Curl predicador máquina',sets:3,reps:'10-12',rest:75},
    {name:'Curl alterno mancuernas',sets:3,reps:'10/lado',rest:75},
    {name:'Curl concentrado',sets:3,reps:'12',rest:60},
  ],
  'Tríceps':[
    {name:'Extensión overhead cable',sets:3,reps:'10-12',rest:90,hint:'cabeza larga estirada'},
    {name:'Extensión overhead mancuerna',sets:3,reps:'10-12',rest:90},
    {name:'Pressdown cuerda',sets:3,reps:'12-15',rest:75},
    {name:'Press cerrado barra',sets:3,reps:'8-10',rest:120},
    {name:'Fondos (torso vertical)',sets:3,reps:'8-12',rest:120},
    {name:'Skullcrusher EZ',sets:3,reps:'10-12',rest:90},
    {name:'Extensión tríceps máquina',sets:3,reps:'12-15',rest:75},
    {name:'Kickback mancuerna',sets:3,reps:'12-15',rest:60},
  ],
  'Cuádriceps':[
    {name:'Sentadilla barra',sets:4,reps:'5-6',rest:210,hint:'RIR 1-2'},
    {name:'Hack squat',sets:4,reps:'6-8',rest:180},
    {name:'Prensa pies bajos',sets:3,reps:'8-10',rest:150},
    {name:'Prensa pies altos',sets:3,reps:'10-12',rest:150},
    {name:'Extensión cuádriceps unilateral',sets:3,reps:'12-15',rest:75,hint:'parcial estirada'},
    {name:'Sentadilla búlgara',sets:3,reps:'8-10/pierna',rest:120},
    {name:'Step-up controlado',sets:3,reps:'10/pierna',rest:90},
    {name:'Sissy squat asistido',sets:3,reps:'10-12',rest:75},
    {name:'Goblet squat',sets:3,reps:'12-15',rest:90},
  ],
  'Isquiotibiales':[
    {name:'Peso muerto rumano (RDL)',sets:3,reps:'6-8',rest:180},
    {name:'Stiff-leg deadlift',sets:3,reps:'8-10',rest:150},
    {name:'Buenos días barra',sets:3,reps:'8-10',rest:150},
    {name:'Curl femoral sentado',sets:3,reps:'10-12',rest:90,hint:'más hipertrofia que tumbado'},
    {name:'Curl femoral tumbado',sets:3,reps:'10-12',rest:90},
    {name:'Hiperextensiones 45°',sets:3,reps:'12-15',rest:75},
    {name:'Nordic curl asistido',sets:3,reps:'6-8',rest:120},
  ],
  'Glúteos':[
    {name:'Hip thrust barra',sets:4,reps:'6-8',rest:180},
    {name:'Hip thrust unilateral',sets:3,reps:'8-10/pierna',rest:120},
    {name:'B-stance hip thrust',sets:3,reps:'10-12',rest:120},
    {name:'Abducción máquina',sets:3,reps:'15-20',rest:60},
    {name:'Patada de glúteo máquina',sets:3,reps:'15-20',rest:60},
    {name:'Zancadas',sets:3,reps:'10/pierna',rest:90},
  ],
  'Gemelos':[
    {name:'Gemelo de pie',sets:4,reps:'8-12',rest:75,hint:'pausa 2s'},
    {name:'Gemelo sentado',sets:4,reps:'15-20',rest:60},
    {name:'Gemelo en prensa',sets:4,reps:'15-20',rest:60},
  ],
  'Core':[
    {name:'Cable crunch (polea)',sets:3,reps:'10-12',rest:60},
    {name:'Rueda abdominal',sets:3,reps:'8-12',rest:60},
    {name:'Leg raise colgado',sets:3,reps:'8-12',rest:60},
    {name:'Pallof press (polea)',sets:3,reps:'10/lado',rest:60},
    {name:'Copenhagen plank',sets:2,reps:'20s/lado',rest:45,type:'time'},
    {name:'Dead bug con carga',sets:3,reps:'10/lado',rest:60},
    {name:'Woodchopper polea',sets:3,reps:'10/lado',rest:60},
    {name:'Side plank',sets:3,reps:'30s/lado',rest:45,type:'time'},
    {name:'Plancha con peso',sets:3,reps:'40s',rest:60,type:'time'},
    {name:'Cable crunch de pie',sets:3,reps:'12-15',rest:60},
  ],
  'Cardio':[
    {name:'LISS bici/elíptica',sets:1,reps:'30-40min',rest:0,type:'time',hint:'65-75% FCmax'},
    {name:'Cinta inclinada',sets:1,reps:'30min',rest:0,type:'time',hint:'10-12% inclinación, 4km/h'},
    {name:'Remo ergómetro LISS',sets:1,reps:'20-30min',rest:0,type:'time'},
    {name:'HIIT bici',sets:1,reps:'6×30s/90s',rest:0,type:'time',hint:'máx sprint + suave'},
  ],
};
